#MySQL
spring:
  datasource:
    url: jdbc:mysql://13.127.162.79:3306/ashokitmini02?useSSL=false
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
 

#Context path

server:
  servlet:
    context-path: "/user"

#Port

  port: 9191


#Mail Properties

#mail:
 # host: "smtp.gmail.com"
  #port: "587"
  #username: "to.test.mail.poc@gmail.com"
  #password: "Iamatboi@1234"
  #properties:
   #          mail:
    #              smtp:
     #                  auth: true
      #                 connectiontimeout: 5000
       #                timeout: 5000
        #               writetimeout: 5000
         #              starttls.enable: true

  
#App Messages 

app:
    messages:
             greetmessages: Hello User !!!! Welcome to our page
             usersuccessfullyregistered: USER REGISTERED SUCCESSFULLY!!!!!
             userregistrationfailed: USER FAILED TO REGISTER
             duplicate: THIS EMAIL IS ALREADY EXIST!!!!!
             unlock_success: USER UNLOCKED SUCCESSFULLY PLEASE LOGIN WITH NEW PASSWORD
             unlock_failed: USER UNLOCKED FAILED
             