#MySQL
spring:
  datasource:
    url: jdbc:mysql://15.206.147.16:3306/ashokitmini02?useSSL=false
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
 

#Context path

server:
  servlet:
    context-path: "/user"

#Port

  port: 9191


#Mail Properties

mail:
  host: "smtp.gmail.com"
  port: "587"
  username: "saddam.md@gmail.com"
  password: "Heiwa@1234"
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true

 
#App Messages 

app:
    messages:
             greetmessages: Hello User !!!! Welcome to our page